// Generated by scripts/generate-rust-replay.py from fixtures/random.json.
use acausal::{Rng, RngState, Seed, Weighted};
#[test]
fn int_d6_x16() {
    let mut rng = Rng::from_legacy(Seed::Scalar(42), 2000).unwrap();
    assert_eq!(rng.int(1, 6).unwrap(), 3);
    assert_eq!(rng.uses(), 2001);
    assert_eq!(rng.int(1, 6).unwrap(), 2);
    assert_eq!(rng.uses(), 2002);
    assert_eq!(rng.int(1, 6).unwrap(), 4);
    assert_eq!(rng.uses(), 2003);
    assert_eq!(rng.int(1, 6).unwrap(), 6);
    assert_eq!(rng.uses(), 2004);
    assert_eq!(rng.int(1, 6).unwrap(), 2);
    assert_eq!(rng.uses(), 2005);
    assert_eq!(rng.int(1, 6).unwrap(), 1);
    assert_eq!(rng.uses(), 2006);
    assert_eq!(rng.int(1, 6).unwrap(), 6);
    assert_eq!(rng.uses(), 2007);
    assert_eq!(rng.int(1, 6).unwrap(), 3);
    assert_eq!(rng.uses(), 2008);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.int(1, 6).unwrap(), 1);
    assert_eq!(rng.uses(), 2009);
    assert_eq!(rng.int(1, 6).unwrap(), 3);
    assert_eq!(rng.uses(), 2010);
    assert_eq!(rng.int(1, 6).unwrap(), 3);
    assert_eq!(rng.uses(), 2011);
    assert_eq!(rng.int(1, 6).unwrap(), 1);
    assert_eq!(rng.uses(), 2012);
    assert_eq!(rng.int(1, 6).unwrap(), 4);
    assert_eq!(rng.uses(), 2013);
    assert_eq!(rng.int(1, 6).unwrap(), 4);
    assert_eq!(rng.uses(), 2014);
    assert_eq!(rng.int(1, 6).unwrap(), 6);
    assert_eq!(rng.uses(), 2015);
    assert_eq!(rng.int(1, 6).unwrap(), 4);
    assert_eq!(rng.uses(), 2016);
}
#[test]
fn int_wide_ranges() {
    let mut rng = Rng::from_legacy(Seed::Scalar(42), 2000).unwrap();
    assert_eq!(rng.int(0, 0).unwrap(), 0);
    assert_eq!(rng.uses(), 2000);
    assert_eq!(rng.int(-5, 5).unwrap(), -3);
    assert_eq!(rng.uses(), 2001);
    assert_eq!(rng.int(0, 255).unwrap(), 11);
    assert_eq!(rng.uses(), 2002);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.int(0, 65535).unwrap(), 1341);
    assert_eq!(rng.uses(), 2003);
    assert_eq!(rng.int(0, 2147483647).unwrap(), 1967828559);
    assert_eq!(rng.uses(), 2004);
    assert_eq!(rng.int(1000000, 2000000).unwrap(), 1270066);
    assert_eq!(rng.uses(), 2005);
}
#[test]
fn float_alias_matches_real() {
    let mut rng = Rng::from_legacy(Seed::Scalar(7), 2000).unwrap();
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.08378587007198324);
    assert_eq!(rng.uses(), 2002);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.526152908756173);
    assert_eq!(rng.uses(), 2004);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.38173460826591166);
    assert_eq!(rng.uses(), 2006);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.8182954760580945);
    assert_eq!(rng.uses(), 2008);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.2839720705188804);
    assert_eq!(rng.uses(), 2010);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.3996656833159823);
    assert_eq!(rng.uses(), 2012);
}
#[test]
fn bool_thresholds() {
    let mut rng = Rng::from_legacy(Seed::Scalar(99), 2000).unwrap();
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2002);
    assert!(rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2004);
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2006);
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2008);
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2010);
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2012);
    assert!(rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2014);
    assert!(!rng.bool(0.5).unwrap());
    assert_eq!(rng.uses(), 2016);
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2018);
    assert!(!rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2020);
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2022);
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2024);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2026);
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2028);
    assert!(!rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2030);
    assert!(rng.bool(0.9).unwrap());
    assert_eq!(rng.uses(), 2032);
    assert!(!rng.bool(0.0).unwrap());
    assert_eq!(rng.uses(), 2034);
    assert!(!rng.bool(0.0).unwrap());
    assert_eq!(rng.uses(), 2036);
    assert!(!rng.bool(0.0).unwrap());
    assert_eq!(rng.uses(), 2038);
    assert!(!rng.bool(0.0).unwrap());
    assert_eq!(rng.uses(), 2040);
    assert!(rng.bool(1.0).unwrap());
    assert_eq!(rng.uses(), 2042);
    assert!(rng.bool(1.0).unwrap());
    assert_eq!(rng.uses(), 2044);
    assert!(rng.bool(1.0).unwrap());
    assert_eq!(rng.uses(), 2046);
    assert!(rng.bool(1.0).unwrap());
    assert_eq!(rng.uses(), 2048);
}
#[test]
fn pick_array_and_slice() {
    let mut rng = Rng::from_legacy(Seed::Scalar(250), 2000).unwrap();
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "f"
    );
    assert_eq!(rng.uses(), 2001);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "c"
    );
    assert_eq!(rng.uses(), 2002);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "f"
    );
    assert_eq!(rng.uses(), 2003);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "f"
    );
    assert_eq!(rng.uses(), 2004);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "b"
    );
    assert_eq!(rng.uses(), 2005);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "b"
    );
    assert_eq!(rng.uses(), 2006);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "e"
    );
    assert_eq!(rng.uses(), 2007);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(0, 5).unwrap() as usize],
        "c"
    );
    assert_eq!(rng.uses(), 2008);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2009);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "c"
    );
    assert_eq!(rng.uses(), 2010);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2011);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2012);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "e"
    );
    assert_eq!(rng.uses(), 2013);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(2, 4).unwrap() as usize],
        "c"
    );
    assert_eq!(rng.uses(), 2014);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(3, 3).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2014);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(3, 3).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2014);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(3, 3).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2014);
    assert_eq!(
        ["a", "b", "c", "d", "e", "f"][rng.int(3, 3).unwrap() as usize],
        "d"
    );
    assert_eq!(rng.uses(), 2014);
}
#[test]
fn pick_weighted_with_and_without_mask() {
    let mut rng = Rng::from_legacy(Seed::Scalar(250), 2000).unwrap();
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2002);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2004);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2006);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2008);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2010);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2012);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2014);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2016);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2018);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &[])
            .unwrap(),
        "red"
    );
    assert_eq!(rng.uses(), 2020);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2022);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2024);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "strawberry"
    );
    assert_eq!(rng.uses(), 2026);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2028);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2030);
    assert_eq!(
        *Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red"])
            .unwrap(),
        "auburn"
    );
    assert_eq!(rng.uses(), 2032);
    assert!(
        Weighted::new(vec![("red", 55.0), ("auburn", 25.0), ("strawberry", 20.0)])
            .unwrap()
            .draw_excluding(&mut rng, &["red", "auburn", "strawberry"])
            .is_err()
    );
    assert_eq!(rng.uses(), 2032);
    assert!(Weighted::new(vec![("a", 1.0), ("b", 0.0), ("c", -3.0), ("d", 2.0)]).is_err());
}
#[test]
fn explicit_uses_skips_prewarm() {
    let mut rng = Rng::from_legacy(Seed::Scalar(250), 100).unwrap();
    assert_eq!(rng.int(0, 1000).unwrap(), 182);
    assert_eq!(rng.uses(), 101);
    assert_eq!(rng.int(0, 1000).unwrap(), 763);
    assert_eq!(rng.uses(), 102);
    assert_eq!(rng.int(0, 1000).unwrap(), 481);
    assert_eq!(rng.uses(), 103);
    assert_eq!(rng.int(0, 1000).unwrap(), 467);
    assert_eq!(rng.uses(), 104);
    assert_eq!(rng.int(0, 1000).unwrap(), 991);
    assert_eq!(rng.uses(), 105);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.int(0, 1000).unwrap(), 758);
    assert_eq!(rng.uses(), 106);
    assert_eq!(rng.int(0, 1000).unwrap(), 19);
    assert_eq!(rng.uses(), 107);
    assert_eq!(rng.int(0, 1000).unwrap(), 334);
    assert_eq!(rng.uses(), 108);
    assert_eq!(rng.int(0, 1000).unwrap(), 278);
    assert_eq!(rng.uses(), 109);
    assert_eq!(rng.int(0, 1000).unwrap(), 990);
    assert_eq!(rng.uses(), 110);
}
#[test]
fn explicit_uses_deep() {
    let mut rng = Rng::from_legacy(Seed::Scalar(250), 5000).unwrap();
    assert_eq!(rng.int(0, 1000).unwrap(), 754);
    assert_eq!(rng.uses(), 5001);
    assert_eq!(rng.int(0, 1000).unwrap(), 174);
    assert_eq!(rng.uses(), 5002);
    assert_eq!(rng.int(0, 1000).unwrap(), 291);
    assert_eq!(rng.uses(), 5003);
    assert_eq!(rng.int(0, 1000).unwrap(), 202);
    assert_eq!(rng.uses(), 5004);
    assert_eq!(rng.int(0, 1000).unwrap(), 83);
    assert_eq!(rng.uses(), 5005);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.int(0, 1000).unwrap(), 888);
    assert_eq!(rng.uses(), 5006);
    assert_eq!(rng.int(0, 1000).unwrap(), 226);
    assert_eq!(rng.uses(), 5007);
    assert_eq!(rng.int(0, 1000).unwrap(), 979);
    assert_eq!(rng.uses(), 5008);
    assert_eq!(rng.int(0, 1000).unwrap(), 32);
    assert_eq!(rng.uses(), 5009);
    assert_eq!(rng.int(0, 1000).unwrap(), 622);
    assert_eq!(rng.uses(), 5010);
}
#[test]
fn array_seed() {
    let mut rng = Rng::from_legacy(Seed::Words(vec![1, 2, 3, 4]), 2000).unwrap();
    assert_eq!(rng.int(0, 999).unwrap(), 79);
    assert_eq!(rng.uses(), 2001);
    assert_eq!(rng.int(0, 999).unwrap(), 308);
    assert_eq!(rng.uses(), 2002);
    assert_eq!(rng.int(0, 999).unwrap(), 437);
    assert_eq!(rng.uses(), 2003);
    assert_eq!(rng.int(0, 999).unwrap(), 327);
    assert_eq!(rng.uses(), 2004);
    assert_eq!(rng.int(0, 999).unwrap(), 480);
    assert_eq!(rng.uses(), 2005);
    assert_eq!(rng.int(0, 999).unwrap(), 385);
    assert_eq!(rng.uses(), 2006);
    rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();
    assert_eq!(rng.int(0, 999).unwrap(), 257);
    assert_eq!(rng.uses(), 2007);
    assert_eq!(rng.int(0, 999).unwrap(), 123);
    assert_eq!(rng.uses(), 2008);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.18209697408146575);
    assert_eq!(rng.uses(), 2010);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.12201762192097954);
    assert_eq!(rng.uses(), 2012);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.8875062977552655);
    assert_eq!(rng.uses(), 2014);
    assert_eq!(rng.float(0.0, 1.0).unwrap(), 0.8953029569298521);
    assert_eq!(rng.uses(), 2016);
}
