#!/usr/bin/env python3
"""Generate primitive replay tests from the existing TS reference fixture."""
import json
from pathlib import Path
import re
import subprocess

root = Path(__file__).resolve().parents[1]
cases = json.loads((root / "fixtures/random.json").read_text())["cases"]
lines = ["// Generated by scripts/generate-rust-replay.py from fixtures/random.json.", "use acausal::{Rng, RngState, Seed, Weighted};"]
skipped = []

def string(value):
    return json.dumps(value, ensure_ascii=False)

def number(value):
    return repr(float(value))

for case in cases:
    if any(s["op"] in ("real", "float") and len(s["args"]) > 2 and s["args"][2] for s in case["steps"]):
        skipped.append(case["name"] + ": legacy inclusive float API")
        continue
    name = re.sub(r"[^a-zA-Z0-9_]", "_", case["name"])
    seed = case["seed"]
    seed_expr = "Seed::Words(vec![" + ",".join(map(str, seed)) + "])" if isinstance(seed, list) else f"Seed::Scalar({seed})"
    lines += ["#[test]", f"fn {name}() {{", f"let mut rng = Rng::from_legacy({seed_expr}, {case.get('uses', 2000)}).unwrap();"]
    for index, step in enumerate(case["steps"]):
        args, value, op = step["args"], step.get("value"), step["op"]
        if op == "int":
            lines.append(f"assert_eq!(rng.int({args[0]}, {args[1]}).unwrap(), {value});")
        elif op in ("real", "float"):
            lines.append(f"assert_eq!(rng.float({number(args[0])}, {number(args[1])}).unwrap(), {number(value)});")
        elif op == "bool":
            lines.append(f"assert!({'!' if not value else ''}rng.bool({number(args[0])}).unwrap());")
        elif op == "pick":
            items = "[" + ",".join(map(string, args[0])) + "]"
            begin = args[1] if len(args) > 1 and args[1] is not None else 0
            end = args[2] if len(args) > 2 and args[2] is not None else len(args[0])
            lines.append(f"assert_eq!({items}[rng.int({begin}, {end - 1}).unwrap() as usize], {string(value)});")
        elif op == "pickWeighted":
            entries = "vec![" + ",".join(f"({string(k)}, {number(v)})" for k,v in args[0].items()) + "]"
            if any(v < 0 for v in args[0].values()):
                lines.append(f"assert!(Weighted::new({entries}).is_err());")
                skipped.append(case["name"] + f": prefix through step {index}, negative weights now rejected")
                break
            mask = "&[" + ",".join(map(string, args[1] if len(args) > 1 and args[1] is not None else [])) + "]"
            if value is None:
                lines.append(f"assert!(Weighted::new({entries}).unwrap().draw_excluding(&mut rng, {mask}).is_err());")
            else:
                lines.append(f"assert_eq!(*Weighted::new({entries}).unwrap().draw_excluding(&mut rng, {mask}).unwrap(), {string(value)});")
        else:
            raise ValueError(op)
        lines.append(f"assert_eq!(rng.uses(), {step['state']['uses']});")
        if case.get("resumeAt", max(1, len(case["steps"]) // 2)) == index + 1:
            lines.append("rng = Rng::from_state(RngState::decode(&rng.snapshot().encode()).unwrap()).unwrap();")
    lines.append("}")

(root / "tests").mkdir(exist_ok=True)
(root / "tests/legacy_rng.rs").write_text("\n".join(lines) + "\n")
subprocess.run(["rustfmt", "--edition", "2024", str(root / "tests/legacy_rng.rs")], check=True)
print("Generated primitive replay tests; intentional exclusions:", skipped)
